### ISSUE TITLE
Required version of Vault missing from readme

### ISSUE THREAD

**Issue by nicholas-marchini** [hashicorp/vault-plugin-database-redis-elasticache#21]
Hi, I cannot see anywhere the minimum version of vault that is needed to use this plugin, can you add that to the readme please?

**Comment by nicholas-marchini** [comment]
Can anyone answer this please?

**Comment by maxcoulombe** [comment]
Hi, the minimal version is Vault v1.12.0+

I'll add this to the readme that's a good point.

**Comment by maxcoulombe** [comment]
Readme was updated to indicate the minimum Vault version required for the plugin to be built-in. Thanks for the question hope it clears things up for others as well!
